// Objective-C API for talking to github.com/scisci/gomobile-static-test/lib Go package.
//   gobind -lang=objc github.com/scisci/gomobile-static-test/lib
//
// File is generated by gobind. Do not edit.

#ifndef __GoLib_H__
#define __GoLib_H__

#include <Foundation/Foundation.h>

@class GoLibObject;

@interface GoLibObject : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (BOOL)Do:(NSString*)something error:(NSError**)error;
@end

FOUNDATION_EXPORT GoLibObject* GoLibNewObject(NSString* value);

#endif
